[package]
name = "rust-database"
version = "1.0.0"
edition = "2021"

[dependencies]
diesel = { version = "2.1.6", features = ["postgres"] }
diesel_migrations = "2.1.0"
dotenv = "0.15.0"
serde_json = "1.0.116"
redis = { version = "0.25.3", features = ["tls-native-tls"] }