version: '3.8'

services:
  database-service: 
    container_name: database-service
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}