name: Rust Application Deployment

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env

      - name: Build docker compose
        run: docker compose up -d

      - name: Clean images
        run: docker image prune -f
